import { WorksheetOptions } from './types'

export interface WorksheetPageData {
  slug: string
  titleUrdu: string
  titleEn: string
  metaDescription: string
  keywords: string[]
  intro: string
  lines: string[]
  defaultOpts: Partial<WorksheetOptions>
}

export const WORKSHEET_PAGES: WorksheetPageData[] = [
  {
    slug: 'huroof-e-tahaji',
    titleUrdu: 'حروف تہجی',
    titleEn: 'Urdu Alphabet — Huroof e Tahaji',
    metaDescription: 'Free printable Urdu alphabet handwriting worksheet. Practice writing all 35 Urdu letters in Nastaleeq script. Perfect for playgroup and kindergarten.',
    keywords: ['urdu alphabet worksheet', 'huroof e tahaji', 'اردو حروف تہجی', 'urdu letters tracing', 'urdu writing practice'],
    intro: 'اردو حروف تہجی سیکھنے کے لیے یہ ورک شیٹ بہترین ہے۔ تمام ۳۵ حروف کا خاکہ بنا کر اپنی لکھائی بہتر کریں۔ This worksheet covers all 35 Urdu letters. Ideal for playgroup and KG students learning to write Urdu for the first time.',
    lines: ['ا  ب  پ  ت  ٹ  ث', 'ج  چ  ح  خ  د  ڈ', 'ذ  ر  ڑ  ز  ژ  س', 'ش  ص  ض  ط  ظ  ع', 'غ  ف  ق  ک  گ  ل', 'م  ن  و  ہ  ی  ے'],
    defaultOpts: { difficultyPreset: 'playgroup', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'bismillah',
    titleUrdu: 'بسم اللہ الرحمٰن الرحیم',
    titleEn: 'Bismillah Handwriting Worksheet',
    metaDescription: 'Free printable Bismillah handwriting practice worksheet in Urdu Nastaleeq. Perfect for Islamic school and madrassa students.',
    keywords: ['bismillah worksheet', 'بسم اللہ ورک شیٹ', 'islamic handwriting worksheet', 'urdu quran writing practice'],
    intro: 'بسم اللہ الرحمٰن الرحیم ہر نیک کام کی ابتدا ہے۔ اس ورک شیٹ میں بسم اللہ کی خوبصورت لکھائی کی مشق کریں۔ Practice writing Bismillah in beautiful Nastaleeq script. Suitable for all ages.',
    lines: ['بِسْمِ اللّٰہِ الرَّحْمٰنِ الرَّحِیْمِ'],
    defaultOpts: { difficultyPreset: 'kg', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'surah-al-fatiha',
    titleUrdu: 'سورۃ الفاتحہ',
    titleEn: 'Surah Al-Fatiha Handwriting Worksheet',
    metaDescription: 'Free printable Surah Al-Fatiha handwriting worksheet in Urdu/Arabic Nastaleeq script. Practice writing the opening chapter of the Quran.',
    keywords: ['surah fatiha worksheet', 'سورۃ الفاتحہ ورک شیٹ', 'quran handwriting practice', 'islamic worksheet urdu'],
    intro: 'سورۃ الفاتحہ قرآن مجید کی پہلی سورت ہے جو ہر نماز میں پڑھی جاتی ہے۔ اس ورک شیٹ میں سورۃ الفاتحہ کی مشق کریں۔ Practice writing Surah Al-Fatiha verse by verse.',
    lines: ['بِسْمِ اللّٰہِ الرَّحْمٰنِ الرَّحِیْمِ', 'اَلْحَمْدُ لِلّٰہِ رَبِّ الْعٰلَمِیْنَ', 'اَلرَّحْمٰنِ الرَّحِیْمِ', 'مٰلِکِ یَوْمِ الدِّیْنِ', 'اِیَّاکَ نَعْبُدُ وَاِیَّاکَ نَسْتَعِیْنُ', 'اِہْدِنَا الصِّرَاطَ الْمُسْتَقِیْمَ', 'صِرَاطَ الَّذِیْنَ اَنْعَمْتَ عَلَیْہِمْ', 'غَیْرِ الْمَغْضُوْبِ عَلَیْہِمْ وَلَا الضَّآلِّیْنَ'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'surah-al-ikhlas',
    titleUrdu: 'سورۃ الاخلاص',
    titleEn: 'Surah Al-Ikhlas Handwriting Worksheet',
    metaDescription: 'Free printable Surah Al-Ikhlas handwriting worksheet. Practice writing this important short surah in beautiful Nastaleeq script.',
    keywords: ['surah ikhlas worksheet', 'سورۃ الاخلاص ورک شیٹ', 'quran writing worksheet urdu'],
    intro: 'سورۃ الاخلاص قرآن مجید کی مختصر لیکن بہت اہم سورت ہے۔ اس سورت کی باقاعدہ مشق سے لکھائی بہتر ہوتی ہے۔',
    lines: ['قُلْ ہُوَ اللّٰہُ اَحَدٌ', 'اَللّٰہُ الصَّمَدُ', 'لَمْ یَلِدْ وَلَمْ یُوْلَدْ', 'وَلَمْ یَکُنْ لَّہٗ کُفُوًا اَحَدٌ'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'kalima-tayyiba',
    titleUrdu: 'کلمہ طیبہ',
    titleEn: 'Kalima Tayyiba Handwriting Worksheet',
    metaDescription: 'Free printable Kalima Tayyiba handwriting worksheet in Urdu Nastaleeq. Practice writing the first Kalima for Islamic studies.',
    keywords: ['kalima tayyiba worksheet', 'کلمہ طیبہ ورک شیٹ', 'islamic studies worksheet urdu', 'kalima writing practice'],
    intro: 'کلمہ طیبہ اسلام کی بنیاد ہے۔ اس ورک شیٹ سے بچے کلمے کی خوبصورت لکھائی سیکھ سکتے ہیں۔ Practice writing the Kalima Tayyiba in Nastaleeq script.',
    lines: ['لَآ اِلٰہَ اِلَّا اللّٰہُ مُحَمَّدٌ رَّسُوْلُ اللّٰہِ'],
    defaultOpts: { difficultyPreset: 'kg', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'asma-ul-husna',
    titleUrdu: 'اسماء الحسنیٰ',
    titleEn: 'Asma ul Husna — 99 Names of Allah Worksheet',
    metaDescription: 'Free printable Asma ul Husna handwriting worksheet. Practice writing the 99 beautiful names of Allah in Urdu Nastaleeq.',
    keywords: ['asma ul husna worksheet', 'اسماء الحسنیٰ ورک شیٹ', '99 names of allah worksheet urdu'],
    intro: 'اللہ تعالیٰ کے ننانوے خوبصورت نام — اسماء الحسنیٰ کی لکھائی کی مشق کریں۔ Learning and writing the 99 names of Allah.',
    lines: ['اَللّٰہُ  الرَّحْمٰنُ  الرَّحِیْمُ', 'اَلْمَلِکُ  اَلْقُدُّوْسُ  اَلسَّلَامُ', 'اَلْمُؤْمِنُ  اَلْمُہَیْمِنُ  اَلْعَزِیْزُ', 'اَلْجَبَّارُ  اَلْمُتَکَبِّرُ  اَلْخَالِقُ', 'اَلْبَارِئُ  اَلْمُصَوِّرُ  اَلْغَفَّارُ'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'urdu-numbers',
    titleUrdu: 'اردو گنتی',
    titleEn: 'Urdu Numbers 1-20 Handwriting Worksheet',
    metaDescription: 'Free printable Urdu numbers handwriting worksheet. Practice writing numbers 1-20 in Urdu words. Perfect for grade 1-2 students.',
    keywords: ['urdu numbers worksheet', 'اردو گنتی ورک شیٹ', 'urdu counting writing practice', 'urdu numbers 1 to 20'],
    intro: 'اردو گنتی سیکھیں اور لکھنے کی مشق کریں۔ Practice writing Urdu numbers 1 to 20 in words. Great for Class 1 and 2 students.',
    lines: ['ایک  دو  تین  چار  پانچ', 'چھ  سات  آٹھ  نو  دس', 'گیارہ  بارہ  تیرہ  چودہ  پندرہ', 'سولہ  سترہ  اٹھارہ  انیس  بیس'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'days-of-week',
    titleUrdu: 'ہفتے کے دن',
    titleEn: 'Days of the Week in Urdu Worksheet',
    metaDescription: 'Free printable days of the week in Urdu handwriting worksheet. Practice writing all 7 days in Urdu for school students.',
    keywords: ['days of week urdu worksheet', 'ہفتے کے دن ورک شیٹ', 'urdu days worksheet', 'weekdays urdu writing'],
    intro: 'ہفتے کے ساتوں دنوں کے نام اردو میں لکھنے کی مشق کریں۔ Practice writing all 7 days of the week in Urdu.',
    lines: ['پیر', 'منگل', 'بدھ', 'جمعرات', 'جمعہ', 'ہفتہ', 'اتوار'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'months-of-year',
    titleUrdu: 'مہینوں کے نام',
    titleEn: 'Months of the Year in Urdu Worksheet',
    metaDescription: 'Free printable months of the year in Urdu handwriting worksheet. Practice writing all 12 months in Urdu for school students.',
    keywords: ['months urdu worksheet', 'مہینوں کے نام ورک شیٹ', 'urdu months writing practice'],
    intro: 'سال کے بارہ مہینوں کے نام اردو میں لکھنے کی مشق کریں۔ Practice writing all 12 months in Urdu.',
    lines: ['جنوری  فروری  مارچ', 'اپریل  مئی  جون', 'جولائی  اگست  ستمبر', 'اکتوبر  نومبر  دسمبر'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'colours-urdu',
    titleUrdu: 'رنگوں کے نام',
    titleEn: 'Colours in Urdu Handwriting Worksheet',
    metaDescription: 'Free printable colours in Urdu handwriting worksheet for kids. Practice writing colour names in Urdu Nastaleeq script.',
    keywords: ['colours urdu worksheet', 'رنگوں کے نام ورک شیٹ', 'urdu colours writing practice for kids'],
    intro: 'رنگوں کے اردو نام لکھنے کی مشق کریں۔ Practice writing colour names in Urdu. Perfect for KG and Class 1 students.',
    lines: ['سرخ  نیلا  سبز', 'زرد  سفید  کالا', 'نارنجی  بنفشی  گلابی', 'بھورا  خاکستری  آسمانی'],
    defaultOpts: { difficultyPreset: 'kg', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'body-parts',
    titleUrdu: 'جسم کے اعضاء',
    titleEn: 'Body Parts in Urdu Handwriting Worksheet',
    metaDescription: 'Free printable body parts in Urdu handwriting worksheet. Practice writing human body part names in Urdu for school students.',
    keywords: ['body parts urdu worksheet', 'جسم کے اعضاء ورک شیٹ', 'urdu body parts writing practice'],
    intro: 'جسم کے اعضاء کے اردو نام لکھنے کی مشق کریں۔ Practice writing human body parts in Urdu.',
    lines: ['سر  آنکھ  کان', 'ناک  منہ  دانت', 'گردن  کندھا  بازو', 'ہاتھ  پیٹ  پیر', 'انگلی  ناخن  گھٹنا'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'animals-urdu',
    titleUrdu: 'جانوروں کے نام',
    titleEn: 'Animals in Urdu Handwriting Worksheet',
    metaDescription: 'Free printable animals in Urdu handwriting worksheet for kids. Practice writing animal names in Urdu for KG and primary school.',
    keywords: ['animals urdu worksheet', 'جانوروں کے نام ورک شیٹ', 'urdu animals writing practice kids'],
    intro: 'جانوروں کے اردو نام لکھنے کی مشق کریں۔ Practice writing animal names in Urdu. Fun and educational for young learners.',
    lines: ['شیر  ہاتھی  گھوڑا', 'گائے  بکری  بھیڑ', 'کتا  بلی  خرگوش', 'مرغی  بطخ  کوا', 'مچھلی  کچھوا  سانپ'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'fruits-urdu',
    titleUrdu: 'پھلوں کے نام',
    titleEn: 'Fruits in Urdu Handwriting Worksheet',
    metaDescription: 'Free printable fruits in Urdu handwriting worksheet. Practice writing fruit names in Urdu for primary school students.',
    keywords: ['fruits urdu worksheet', 'پھلوں کے نام ورک شیٹ', 'urdu fruits writing practice'],
    intro: 'پھلوں کے اردو نام لکھنے کی مشق کریں۔ Practice writing fruit names in Urdu. Great for Class 1-2 students.',
    lines: ['سیب  کیلا  آم', 'انگور  تربوز  خربوزہ', 'انار  امرود  لیچی', 'آڑو  بیر  شہتوت'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'naskh', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'lab-pe-aati-hai',
    titleUrdu: 'لب پہ آتی ہے دعا',
    titleEn: 'Lab Pe Aati Hai Dua — Allama Iqbal',
    metaDescription: 'Free printable Lab Pe Aati Hai Dua by Allama Iqbal handwriting worksheet. Practice writing this famous Urdu poem for school assemblies.',
    keywords: ['lab pe aati hai worksheet', 'لب پہ آتی ہے دعا', 'allama iqbal poem worksheet urdu', 'urdu poem writing practice'],
    intro: 'علامہ اقبال کی مشہور نظم "لب پہ آتی ہے دعا" کی لکھائی مشق کریں۔ Practice writing this beloved poem recited in school assemblies across Pakistan.',
    lines: ['لب پہ آتی ہے دعا بن کے تمنا میری', 'زندگی شمع کی صورت ہو خدایا میری', 'دور دنیا کا مرے دم سے اندھیرا ہو جائے', 'ہر جگہ میرے چمکنے سے اجالا ہو جائے'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
  {
    slug: 'daily-duas',
    titleUrdu: 'روزانہ کی دعائیں',
    titleEn: 'Daily Duas Handwriting Worksheet',
    metaDescription: 'Free printable daily duas handwriting worksheet in Urdu. Practice writing morning, eating and sleeping duas for Islamic studies.',
    keywords: ['daily duas worksheet', 'روزانہ دعائیں ورک شیٹ', 'islamic duas writing practice urdu', 'madrassa worksheet'],
    intro: 'روزمرہ کی ضروری دعاؤں کی لکھائی مشق کریں۔ Practice writing essential daily duas used in everyday life. Ideal for madrassa and Islamic school students.',
    lines: ['بِسْمِ اللّٰہِ (کھانے سے پہلے)', 'اَلْحَمْدُ لِلّٰہِ (کھانے کے بعد)', 'اَللّٰہُمَّ اِنِّیْ اَعُوْذُبِکَ (صبح کی دعا)', 'بِسْمِکَ اللّٰہُمَّ (سونے کی دعا)', 'اَلسَّلَامُ عَلَیْکُمْ (ملتے وقت)', 'جَزَاکَ اللّٰہُ خَیْرًا (شکریہ)'],
    defaultOpts: { difficultyPreset: 'class1-3', fontStyle: 'nastaleeq', worksheetStyle: 'trace-blank' },
  },
]
